python3 main.py \
    --pkl_path /scratch/samgain/CVS/ \
    --model vit \
    --num_frames 3 \
    --group 1 \
    --epochs 100 \
    --batch_size 32 \
    --seed 1 \
    --save /scratch/samgain/CVS/ \
    --gpu 0 \
    --lr 5e-5 \
    --reg 0.01 \
    --dropout 0.5 \
    --pretrained